project:
  type: website

website:
  title: "Spencer Paragas"
  navbar:
    right:
      - text: Blog
        href: blog.qmd
      - icon: github
        href: https://github.com/skparagas/CS-5805-Final-Project
      - icon: twitter
        href: https://twitter.com/ParagasSpencer
format:
  html:
    theme: minty
    css: styles.css

editor: visual

