project:
  type: website

website:
  title: "Spencer Paragas"
  navbar:
    right:
      - text: Blog
        href: blog/blog.qmd
      - icon: github
        href: https://github.com/skparagas/CS-5805-Final-Project
      - icon: twitter
        href: https://twitter.com/ParagasSpencer
format:
  html:
    page-layout: full
    theme: 
      light: [minty]
      dark: [darkly]
    css: styles.css
    grid: 
      sidebar-width: 150px
      body-width: 1800px
      margin-width: 250px
    code-tools: true
    output-file: index.html

editor: source

execute:
  freeze: true
  cache: true
  warning: false
  echo: fenced
